version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: laager-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laager_voting
      POSTGRES_USER: laager_user
      POSTGRES_PASSWORD: laager_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laager_user -d laager_voting"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - laager-network

  redis:
    image: redis:7-alpine
    container_name: laager-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - laager-network

  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    container_name: laager-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: laager_user
      RABBITMQ_DEFAULT_PASS: laager_password
      RABBITMQ_DEFAULT_VHOST: laager_vhost
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - laager-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: laager-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@laager.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - laager-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  laager-network:
    driver: bridge
